# Section 3.4: the SIR model of Section 5.2 built with ModelingToolkit.jl and with Catalyst.jl.
# Direction of interoperability: ModelingToolkit and Catalyst models are converted to the
# StructuralIdentifiability.jl representation (not the other way around).
using ModelingToolkit
using Catalyst
include("common.jl")
Random.seed!(1)
println("ModelingToolkit.jl ", pkgversion(ModelingToolkit), " | Catalyst.jl ", pkgversion(Catalyst))

# --- (a) ModelingToolkit System ---------------------------------------------------------
@independent_variables t
D = Differential(t)
@parameters beta gamma
@variables S(t) I(t) R(t) y(t)
eqs = [D(S) ~ -beta * S * I,
       D(I) ~  beta * S * I - gamma * I,
       D(R) ~  gamma * I]
@named sir_mtk = System(eqs, t)

header("ModelingToolkit System, measured y ~ beta*S*I: global identifiability")
report(assess_identifiability(sir_mtk; measured_quantities = [y ~ beta * S * I],
                              loglevel = SI_LOGLEVEL))

header("ModelingToolkit System: identifiable functions")
report_functions(find_identifiable_functions(sir_mtk; measured_quantities = [y ~ beta * S * I],
                                             loglevel = SI_LOGLEVEL))

header("Explicit conversion with mtk_to_si")
si_ode, conversion = mtk_to_si(sir_mtk, [y ~ beta * S * I])
println(si_ode)

# --- (b) Catalyst ReactionSystem --------------------------------------------------------
sir_rn = @reaction_network begin
    beta,  S + I --> 2I
    gamma, I --> R
end
println()
println("Reaction-rate equations generated by Catalyst:")
println(equations(ode_model(sir_rn)))

header("Catalyst ReactionSystem, measured beta*S*I: global identifiability")
report(assess_identifiability(sir_rn;
                              measured_quantities = [sir_rn.beta * sir_rn.S * sir_rn.I],
                              loglevel = SI_LOGLEVEL))

header("Catalyst ReactionSystem, conservation laws kept (remove_conserved = false)")
report(assess_identifiability(sir_rn;
                              measured_quantities = [sir_rn.beta * sir_rn.S * sir_rn.I],
                              remove_conserved = false, loglevel = SI_LOGLEVEL))

header("Catalyst ReactionSystem: identifiable functions")
report_functions(find_identifiable_functions(sir_rn;
                                             measured_quantities = [sir_rn.beta * sir_rn.S * sir_rn.I],
                                             loglevel = SI_LOGLEVEL))

header("Catalyst ReactionSystem converted with make_si_ode")
println(make_si_ode(sir_rn; measured_quantities = [sir_rn.beta * sir_rn.S * sir_rn.I]))
